# Using official python runtime base image
ARG BASE_IMAGE_TAG
FROM python:3.9-slim
ARG OPTION_A
ARG OPTION_B
ENV OPTION_A $OPTION_A \
    OPTION_B $OPTION_B
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . .

EXPOSE 80

CMD ["gunicorn", "app:app", "-b", "0.0.0.0:80", "--log-file", "-", "--access-logfile", "-", "--workers", "4", "--keep-alive", "0"]
